import {RECIPES,ROUTES,STATIONS,STATION_ORDER,SUNDRIES,targetTime,duration,completion,processEstimate,noteCountOf,stationOf,sundriesOf,vatSlotsOf,seasonLeft,seasonLabel,missingSundries} from './processing-engine.js'
const SEASON={spring:'春 · 谷雨 · 水田映晨光',summer:'夏 · 小暑 · 绿稻满田',autumn:'秋 · 秋分 · 金色稻田',winter:'冬 · 冬至 · 雪覆休耕田'}
const STATION_RECIPES=Object.fromEntries(STATION_ORDER.map(k=>[k,Object.keys(RECIPES).filter(r=>stationOf(r)===k)]))
export function createProcessing({getState,dispatch,goFarm}){
 const root=document.querySelector('#processing-root');let selected='riceball',raf=0,started=0,offset=0,lastSave=0,feedback='等待节拍',count=0,countStart=0,guide=0
 const elapsed=()=>Math.max(0,offset+performance.now()-started)
 function stop(){cancelAnimationFrame(raf);raf=0;count=0;}
 function pause(){const dialog=root.querySelector('dialog');if(dialog)dialog.close();guide=0;if(getState().workshop.active?.phase==='running'){const t=elapsed();stop();dispatch({type:'process:pause',elapsed:t},{quiet:true});}stop();render();}
 function tap(){const w=getState().workshop;if(w.active?.phase!=='running')return;const before=w.active.hits.filter(x=>x>0).length;dispatch({type:'process:tap',elapsed:elapsed()},{quiet:true});const after=getState().workshop.active;feedback=after.hits.filter(x=>x>0).length>before?(after.hits.filter(x=>x===1).length>w.active.hits.filter(x=>x===1).length?'精准！米香渐起':'合拍！继续跟上节奏'):'未合拍，再看金色判定线';updateHUD();}
 function updateHUD(){const w=getState().workshop,a=w.active;if(!a)return;const t=a.phase==='running'?Math.min(duration(w),elapsed()):a.elapsed
  root.dataset.rhythm=JSON.stringify({elapsed:Math.round(t),phase:a.phase,completion:Math.round(completion(a)*100),hits:a.hits})
  const progress=root.querySelector('.rhythm-progress span');if(progress)progress.style.width=(t/duration(w)*100)+'%'
  const score=root.querySelector('#rhythm-score');if(score)score.textContent=Math.round(completion(a)*100)+'%'
  const feed=root.querySelector('#rhythm-feedback');if(feed)feed.textContent=feedback
  root.querySelectorAll('.rhythm-note').forEach((n,i)=>{const delta=targetTime(w,i)-t;n.style.left=(50+delta/2000*100)+'%';n.classList.toggle('done',a.hits[i]!==null);n.classList.toggle('perfect',a.hits[i]===1);n.hidden=delta>1050||delta<-1050;})
 }
 function loop(){if(root.hidden||document.hidden){pause();return;}const w=getState().workshop;if(w.active?.phase!=='running'){stop();return;}const t=elapsed();if(t-lastSave>=180){dispatch({type:'process:tick',elapsed:t},{quiet:true});lastSave=t;}
  updateHUD();if(t>=duration(w)){stop();dispatch({type:'process:tick',elapsed:duration(w)},{quiet:true});dispatch({type:'process:finish'});return;}raf=requestAnimationFrame(loop)
 }
 function begin(){count=0;dispatch({type:'process:resume'},{quiet:true});const a=getState().workshop.active;if(!a||a.phase!=='running')return;offset=a.elapsed;started=performance.now();lastSave=offset;feedback='亮点到金线时点击';render();root.querySelector('#rhythm-hit')?.focus({preventScroll:true});raf=requestAnimationFrame(loop);}
 function countdown(){if(root.hidden||document.hidden||!getState().workshop.active){pause();return;}const n=3-Math.floor((performance.now()-countStart)/1000);if(n<=0){begin();return;}count=n;const el=root.querySelector('#rhythm-count');if(el)el.textContent=String(n);raf=requestAnimationFrame(countdown);}
 function startRhythm(){const a=getState().workshop.active;if(!a||a.phase==='running'||count)return;stop();count=3;countStart=performance.now();feedback='准备跟上节奏';render();root.querySelector('.rhythm-game')?.scrollIntoView({behavior:'smooth',block:'center'});raf=requestAnimationFrame(countdown);}
 function guideHTML(){const steps=[['先选科技路线','现代工业产量更高、节奏更快；生态古法节奏舒缓。首批加工开始后路线固定。'],['花技艺点学配方','初始有 2 技艺点。先学饭团或米粉，再解锁后续配方；每批完成度达到 50% 可赚回 1 点。'],['认准器具再上手','石磨、米糕模具、灶台、酿酒缸各管一条工艺线：米糕模具只有三拍，全中出上品；灶台要备蛋或米浆；酿酒缸拌曲后要等两季。亮点到金线时点击或按空格。']],v=steps[guide-1];return `<dialog class="workshop-guide" aria-labelledby="workshop-guide-title"><small>御米作坊 · 新手引导 ${guide} / 3</small><h2 id="workshop-guide-title">${guide}. ${v[0]}</h2><p>${v[1]}</p><p>1. 先选科技路线 → 2. 花技艺点学配方 → 3. 按节拍加工出成品</p>${guide>1?'<button class="text-button" data-guide="back">上一步</button>':''}<button class="farm-primary" data-guide="next">${guide===3?'知道了，开始制作':'下一步'}</button></dialog>`;}
 function closeGuide(){guide=0;dispatch({type:'process:tutorial'});root.querySelector('[data-process="guide"]')?.focus({preventScroll:true});}
 // 包 M2：四件器具各自的状态（在用 / 空闲 / 缸位占用），供器具面板与配方分组用。
 function stationState(w,key){const a=w.active,own=STATION_RECIPES[key]||[],busy=!!a&&stationOf(a.recipe)===key,vats=key==='vat'?w.vats.length:0,slots=key==='vat'?vatSlotsOf(w):0;return {key,busy,vats,slots,own};}
 function stationHTML(w){return STATION_ORDER.map(k=>{const st=STATIONS[k],x=stationState(w,k),labels=x.own.map(r=>RECIPES[r].name).join(' / ')
  const state=k==='vat'?`缸位 ${x.vats} / ${x.slots}`:x.busy?'手上这批就在这':'空闲'
  return `<button type="button" class="station ${x.busy?'busy':''}" data-station="${k}"><i class="st-img"><img src="./assets/img/s-${k}.jpg" alt="${st.name}" loading="lazy" onerror="this.outerHTML='${st.glyph}'"></i><b>${st.name}</b><span>${st.line}</span><small>${labels}</small><em>${state}</em></button>`}).join('')}
 // 包 M2：缸里的酒。每口缸写明投料年月、完成度与还差几季。
 function vatHTML(s,w){const slots=vatSlotsOf(w),cells=[]
  for(const v of w.vats)cells.push(`<div class="vat done"><b>第 ${v.id} 缸</b><span>米酒 ${v.quantity} 瓶 · 拌曲完成度 ${v.completion}%${v.fine?' · 上品':''}</span><small>${seasonLabel(v.putSeason,v.putYear)}入缸 · 还差 ${seasonLeft(v,s.season,s.year)} 季（${seasonLabel(v.readySeason,v.readyYear)}出酒）</small></div>`)
  for(let i=w.vats.length;i<slots;i++)cells.push(`<div class="vat empty"><b>空缸</b><span>拌好曲就能下料</span><small>作坊每扩建一级多一口缸</small></div>`)
  return `<section class="farm-card vat-card"><div class="farm-card-head"><h2>酿酒缸</h2><span>在用 ${w.vats.length} / ${slots} 口 · 两季成酒</span></div><div class="vat-grid">${cells.join('')}</div><p class="recipe-tip">米酒拌曲仍走十二拍；入缸后静候两个季节，跨季自动出酒入库，到时缸位腾出来。卖给酒楼价最高（12 文 / 瓶）。</p></section>`}
 // 包 M2：灶台辅料。缺料时按钮点不动，先在作坊里托人捎带。
 function sundryHTML(w,recipe){const rows=sundriesOf(recipe);if(!rows.length)return ''
  return `<div class="sundry-row"><span>灶上用料</span>${rows.map(([k,n])=>{const p=SUNDRIES[k],have=w.pantry[k]||0;return `<b class="${have>=n?'ok':'lack'}">${p.glyph} ${p.name} ${have} / ${n}</b>`}).join('')}${rows.map(([k,n])=>{const p=SUNDRIES[k];return `<button class="text-button" data-process="buy" data-sundry="${k}" data-count="${n}">捎带 ${p.name} ×${n} · ${p.price*n} 文</button>`}).join('')}</div>`}
 function render(message=''){
  const s=getState(),w=s.workshop,a=w.active;if(a)selected=a.recipe;if(!a)stop();if(document.body.classList.contains('guide-running')||document.body.classList.contains('system-open'))guide=0;else if(!w.completed&&!w.tutorialSeen&&!guide)guide=1
  const r=RECIPES[selected],route=w.route?ROUTES[w.route]:null,learned=w.learned.includes(selected),miss=missingSundries(w,selected)
  root.innerHTML=`<div class="farm-heading"><span>二产加工 · 天工开物</span><h1>御米作坊</h1><p>第 ${s.year} 年 · ${SEASON[s.season]}</p></div><section class="workshop-stats"><div><span>可用稻米</span><strong>${s.rice.toLocaleString()} <small>kg</small></strong></div><div><span>技艺点</span><strong>${w.points}</strong></div><div><span>已学技能</span><strong>${w.learned.length} <small>/ ${Object.keys(RECIPES).length}</small></strong></div><div><span>已完成</span><strong>${w.completed} <small>批</small></strong></div></section>
  <section class="farm-card station-card"><div class="farm-card-head"><h2>作坊四工艺</h2><span>四件器具共用同一套节拍判定</span></div><div class="station-grid">${stationHTML(w)}</div></section>
  <section class="farm-card workshop-efficiency"><div class="farm-card-head"><h2>作坊产出效率</h2><button class="text-button" data-process="guide">查看 3 步引导</button></div><div class="workshop-stats"><div><span>累计消耗稻米</span><strong>${w.stats.riceUsed} <small>kg</small></strong></div><div><span>累计产出食物</span><strong>${w.stats.foodMade} <small>份</small></strong></div><div><span>平均完成度</span><strong>${w.stats.batches?Math.round(w.stats.completionTotal/w.stats.batches)+'%':'—'}</strong></div><div><span>统计已完成</span><strong>${w.stats.batches} <small>批</small></strong></div></div><p class="recipe-tip">${w.stats.legacy?'旧档缺少完整加工历史，从升级后开始统计（含续做批次）。':'本局累计：扣米时计入消耗，成品入库时计入产出；平均完成度仅统计已完成批次。'}米酒每瓶按 1 份成品计，入缸那批要等出酒才计入。</p></section>
  <section class="farm-card route-card"><div class="farm-card-head"><h2>选择科技分支</h2><span>${w.serial?'本局路线已确定':'首批加工前可改选'}</span></div><div class="route-options">${Object.entries(ROUTES).map(([k,v])=>`<button data-process="route" data-route="${k}" ${w.serial?'disabled':''} class="${w.route===k?'selected':''}" aria-pressed="${w.route===k}"><b>${v.name}</b><span>${v.description}</span>${w.route===k?'<em>已选择</em>':''}</button>`).join('')}</div></section>
  <div class="processing-columns"><section class="farm-card skill-card"><div class="farm-card-head"><h2>加工技能树</h2><span>完成度 ≥50% 的每批加工获得 1 技艺点</span></div><p class="skill-path">饭团 → 蛋炒饭 / 米糕 → 酿酒<br>米粉 → 肠粉 / 米线</p><div class="recipe-grid">${Object.entries(RECIPES).map(([k,v])=>{const n=noteCountOf(k),st=STATIONS[stationOf(k)];return `<button data-process="select" data-recipe="${k}" ${a?'disabled':''} class="${selected===k?'selected':''}" aria-pressed="${selected===k}"><i class="rc-img"><img src="./assets/img/p-${k}.jpg" alt="${v.product||v.name}" loading="lazy" onerror="this.outerHTML='${v.glyph}'"></i><b>${v.name}</b><span>${v.rice} kg / 批 · ${n} 拍</span><small>${w.learned.includes(k)?'已学会':'前置：'+(v.requires.length?v.requires.map(p=>RECIPES[p].name).join('、'):'无（入门）')}</small><em class="recipe-station">${st.glyph} ${st.name}${v.premium?' · 可出上品':''}${v.seasons?` · 等 ${v.seasons} 季`:''}${sundriesOf(k).length?' · 需辅料':''}</em></button>`}).join('')}</div><div class="food-inventory"><h3>食物仓库</h3>${Object.entries(RECIPES).map(([k,v])=>`<span>${v.product||v.name}<b>${w.foods[k]} ${v.unit}${w.premium[k]?`（上品 ${w.premium[k]}）`:''}</b></span>`).join('')}</div>${w.vats.length?`<p class="recipe-tip">缸里还存着 ${w.vats.reduce((n,v)=>n+v.quantity,0)} 瓶未出缸的米酒。</p>`:''}</section>
  <section class="farm-card craft-card"><div class="farm-card-head"><h2>${a?'正在制作 · ':''}${r.product||r.name}</h2><span>${r.rice} kg 稻米 / 批 · ${noteCountOf(selected)} 拍 · ${STATIONS[stationOf(selected)].name}</span></div><img class="craft-hero" src="./assets/img/p-${selected}.jpg" alt="${r.product||r.name}" loading="lazy" onerror="this.remove()">${a?rhythmHTML(w):`<div class="recipe-output"><span>基础产出</span><strong>${r.base} <small>${r.unit}</small></strong><p>${route?`本路线可产 ${processEstimate(w,selected,0)}–${processEstimate(w,selected,1)} ${r.unit}，取决于节奏完成度。`:'选择路线后显示预计产量。'}</p></div>${sundryHTML(w,selected)}<p class="recipe-tip">${r.step}时跟随 ${noteCountOf(selected)} 个节拍，点击按钮或按空格。每次加工固定消耗 ${r.rice} kg 稻米${sundriesOf(selected).length?'，并按配方扣下辅料':'；辅料在本版配方中视为已备齐'}。${r.premium?'三拍全中、一次空击都没有，才是「上品」，售价 ×1.5。':''}${r.seasons?'拌好曲入缸，静候两个季节出酒。':''}</p>${!learned?`<button class="farm-primary" data-process="learn" ${!route||w.points<r.cost||r.requires.some(k=>!w.learned.includes(k))?'disabled':''}>学习${r.name} · ${r.cost} 技艺点</button>`:`<button class="farm-primary" data-process="start" ${!route||s.rice<r.rice||miss.length||(r.station==='vat'&&w.vats.length>=vatSlotsOf(w))?'disabled':''}>投入 ${r.rice} kg 稻米，准备加工</button>`}<p class="recipe-tip">${!route?'请先选择上方科技路线。':!learned&&r.requires.some(k=>!w.learned.includes(k))?'需要先学会：'+r.requires.map(k=>RECIPES[k].name).join('、'):s.rice<r.rice?'稻米不足，请返回御田完成秋收。':miss.length?`灶上还差${miss.map(k=>SUNDRIES[k].name).join('、')}，先在上方捎带。`:r.station==='vat'&&w.vats.length>=vatSlotsOf(w)?`缸位占满了（${w.vats.length}/${vatSlotsOf(w)}），等一出酒再来。`:'按开始时扣米扣料；暂停或刷新继续原批次，不再扣。'}</p><button class="text-button" data-process="farm">返回御田</button>`}
  ${!a&&w.last?`<section class="processing-result" role="status"><span>第 ${w.last.id} 批 · ${w.last.cured?'已入缸':'已自动入库'}</span><h3>${w.last.cured?`从 ${w.last.rice??RECIPES[w.last.recipe].rice} kg 稻米拌曲 → 入缸待 ${RECIPES[w.last.recipe].seasons||2} 季出酒`:w.last.fine?`上品${w.last.name}！从 ${w.last.rice??RECIPES[w.last.recipe].rice} kg 稻米 → 得到 ${w.last.quantity} ${w.last.unit}`:`从 ${w.last.rice??RECIPES[w.last.recipe].rice} kg 稻米 → 得到 ${w.last.quantity} ${w.last.unit}${w.last.name}`}</h3><p>${w.last.cured?`米酒在缸里慢慢陈着，跨季自动入库；可前往销售区出售。`:`${RECIPES[w.last.recipe].product||RECIPES[w.last.recipe].name}已入库，可前往销售区出售。`}${w.last.fine?'「上品」按 1.5 倍价出售。':''}</p><p>完成度 ${w.last.completion}% · 精准 ${w.last.perfect} / 合拍 ${w.last.good} / 漏拍 ${w.last.miss}</p><p>消耗 ${w.last.rice} kg · 技艺点 +${w.last.point}</p></section>`:''}
  ${vatHTML(s,w)}
  <p class="farm-message" role="status">${message.replace(/[<>]/g,'')}</p><details class="farm-rules"><summary>加工与节奏规则</summary><p>每批的拍数由器具定：米糕模具三拍，其余十二拍。精准 1 分、合拍 0.65 分、漏拍 0 分；空击每次扣完成度 2.5 个百分点，连续 110ms 内的点击忽略。完成度 = 命中分÷拍数 − 空击扣分（最低 0）。</p><p>产量 = 向下取整〔基础产出 × (0.5 + 完成度) × 路线系数 × (1 − 加工损耗)〕。现代工业系数 1.2；生态古法系数 1.0、节拍和判定更宽松。加工损耗随已学配方数与作坊等级下降（最低 10%），最终至少产出 1 份；不退还投入的稻米与辅料。</p><p>上品：米糕模具三拍全中且无空击，该批即为上品，入库计入「上品份数」，出售时这批按 1.5 倍作价。酿酒缸里的米酒拌曲后要过两个季节才出酒，占用的那口缸在此期间不能用。</p><p>辅料（蛋、米浆）可在作坊里托人从镇上捎带，按市价入库；不是现实烹饪或酿造说明。加工不推进季节；背景与存档当前季节一致。</p></details></section></div>${guide?guideHTML():''}`
  root.querySelectorAll('[data-process]').forEach(b=>b.addEventListener('click',()=>{const action=b.dataset.process
   if(action==='guide'){if(count||getState().workshop.active?.phase==='running')pause();guide=1;render();return;}
   if(action==='select'){selected=b.dataset.recipe;render();return;}
   if(action==='farm'){pause();goFarm();return;}
   if(action==='buy'){dispatch({type:'process:buy',sundry:b.dataset.sundry,count:Number(b.dataset.count)||1});return;}
   if(action==='route')dispatch({type:'process:route',route:b.dataset.route})
   if(action==='learn')dispatch({type:'process:learn',recipe:selected})
   if(action==='start')dispatch({type:'process:start',recipe:selected})
   if(action==='resume')startRhythm();if(action==='pause')pause();if(action==='hit')tap()
  }));root.querySelectorAll('[data-station]').forEach(b=>b.addEventListener('click',()=>{if(getState().workshop.active)return;const own=STATION_RECIPES[b.dataset.station]||[];if(own.length){selected=own[0];render();}}));const dialog=root.querySelector('dialog');if(dialog){dialog.addEventListener('cancel',e=>{e.preventDefault();closeGuide();});dialog.querySelectorAll('[data-guide]').forEach(b=>b.onclick=()=>{if(b.dataset.guide==='back'){guide--;render();}else if(guide<3){guide++;render();}else closeGuide();});dialog.showModal();}updateHUD()
 }
 function rhythmHTML(w){const a=w.active,r=RECIPES[a.recipe],n=a.hits.length,own=r.premium&&a.strays===0&&a.hits.every(h=>h===1);return `<section class="rhythm-game" aria-label="加工节奏小游戏"><div class="rhythm-caption"><span>完成度 <b id="rhythm-score">${Math.round(completion(a)*100)}%</b></span><span>${n} 拍 · ${STATIONS[stationOf(a.recipe)].name} · ${ROUTES[w.route].name}</span></div><div class="rhythm-lane">${count?`<div class="rhythm-countdown" role="status" aria-live="polite"><b id="rhythm-count">${count}</b><span>准备 · 点击 / 空格打节拍</span></div>`:''}<div class="rhythm-target"></div>${a.hits.map((_,i)=>`<i class="rhythm-note" data-note="${i}">${i+1}</i>`).join('')}</div><div class="rhythm-progress"><span></span></div><div class="rhythm-gesture" aria-label="亮点到金线时点击"><svg viewBox="0 0 160 48" aria-hidden="true"><path d="M80 2v44" stroke="#b18127" stroke-width="3"/><circle class="gesture-dot" cx="140" cy="17" r="7" fill="#caa64e"/><path class="gesture-hand" d="M78 43V25q0-5 4-5t4 5v6l4-3 4 4v8l-5 6h-8z" fill="#fff0c5" stroke="#775d2e" stroke-width="2"/></svg><span>亮点到金线时点击 · 或按空格</span></div>${r.premium?`<p class="premium-hint ${own?'on':''}">${own?'眼下全中，保持住就是上品米糕':'三拍全中、不空击才出上品（售价 ×1.5）'}</p>`:''}${r.seasons?`<p class="premium-hint">拌好曲就入缸，还要等 ${r.seasons} 个季节出酒</p>`:''}<p id="rhythm-feedback" aria-live="off">${feedback}</p>${count?'<button class="text-button" data-process="pause">取消倒计时</button>':a.phase==='running'?'<button class="farm-primary rhythm-hit" id="rhythm-hit" data-process="hit">合拍制作 · 点击 / 空格</button><button class="text-button" data-process="pause">暂停加工</button>':`<p class="recipe-tip">本批已扣 ${RECIPES[a.recipe].rice} kg${sundriesOf(a.recipe).length?'与辅料':''}。亮点移动到金色中央线时点击；不要连点。</p><button class="farm-primary" data-process="resume">${a.phase==='ready'?'开始节奏':'继续本批节奏'}</button>`}</section>`;}
 const keydown=e=>{if(e.code!=='Space'||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||root.hidden||guide)return;if(count||getState().workshop.active?.phase==='running'){e.preventDefault();if(!count&&!e.repeat)tap();}}
 addEventListener('keydown',keydown);document.addEventListener('visibilitychange',()=>{if(document.hidden&&(count||getState().workshop.active?.phase==='running'))pause();});addEventListener('pagehide',()=>{const a=getState().workshop.active;if(a?.phase==='running')dispatch({type:'process:pause',elapsed:elapsed()},{quiet:true});stop();})
 return {render,pause,stop}
}
