import {CHAPTERS,chapterLimit} from './story-engine.js'
import {TECHS,TECH_IDS,techReqMiss,techEffects,techNoticeText} from './tech-engine.js'
import {SAVE_KEY} from './farm-engine.js'
const SEASON_CN={spring:'春',summer:'夏',autumn:'秋',winter:'冬'}
// —— 包 I2：科技的宣纸风样式（未解锁 / 研发中 / 已解锁三态 + 分支择路弹层）——
const TECH_CSS=`.tech-tree{margin:14px 0;padding:13px;background:#f8f1de;color:#354437;border:1px solid #ba9e64;border-radius:8px}.tech-tree summary{color:#7a4a1e;font:20px KaiTi,serif;cursor:pointer}.tech-tree .tech-note{font-size:12px;color:#6e634c;line-height:1.75;margin:8px 0}.tech-grid{display:grid;gap:9px;margin-top:10px}.tech-card{border:1px solid #c3cbb0;background:#fdf8ea;border-radius:7px;padding:10px 11px}.tech-card.locked{opacity:.62}.tech-card.running{border-color:#c19b56;background:#fbf3dc}.tech-card.done{border-color:#8a9c6a;background:#eff3e2}.tech-card header{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.tech-card header b{font:19px KaiTi,serif}.tech-card header em{font-style:normal;font-size:11px;color:#8b7a56;border:1px solid #d5c49c;border-radius:9px;padding:1px 7px}.tech-card header i{font-style:normal;font-size:12px;color:#7a5a1e;background:linear-gradient(135deg,#f0dca6,#e8c46e);border-radius:9px;padding:2px 9px;border:1px solid #c9a75a}.tech-tree .tech-card p{font-size:13px;line-height:1.75;margin:6px 0;color:#4a5641}.tech-tree .tech-cost{font-size:12px;color:#7a6a4a}.tech-tree .tech-miss{font-size:12px;color:#b4613f}.tech-tree .tech-effect{font-size:12px;color:#3f5c2f}.tech-track{height:9px;border-radius:9px;background:#e2d9c2;overflow:hidden;margin:7px 0 4px}.tech-track i{display:block;height:100%;background:linear-gradient(90deg,#9c6d2f,#e5c56e);transition:width .4s}.tech-card button,.tech-pick button{border:1px solid #aa915f;border-radius:5px;background:#354b39;color:#fff3d6;padding:8px 11px;margin:3px 3px 0 0;cursor:pointer;font-family:inherit;font-size:13px}.tech-card button:disabled{opacity:.5;cursor:default}.tech-pick{margin-top:12px;padding:12px;border:1px dashed #b99250;border-radius:8px;background:#fdf6e4}.tech-pick h4{font:19px KaiTi,serif;margin:0 0 6px;color:#7a4a1e}.branch-grid{display:grid;gap:8px;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));margin:9px 0}.branch-grid button{display:flex;flex-direction:column;gap:3px;text-align:left;background:#f6f1e0;color:#3b4a35;border:1px solid #c3b083;padding:9px 10px}.branch-grid button[aria-pressed=true]{background:#eef3dd;border-color:#6c8a4c;box-shadow:inset 0 0 0 1px #6c8a4c}.branch-grid button b{font:17px KaiTi,serif}.branch-grid button span{font-size:12px;line-height:1.65}.branch-grid button em{font-style:normal;font-size:11px;color:#5c6b4a}.tech-pick-actions{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin-top:6px}.tech-warn{color:#a4402b;font:15px KaiTi,serif}.tech-notice{margin:10px 0;padding:10px 12px;border-left:4px solid #b99250;background:#fbf3dc;border-radius:0 7px 7px 0;font-size:13px;line-height:1.8;color:#5a4a2e}.tech-notice button{margin-top:6px}`
const esc=t=>String(t??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
export function createStory({getState,dispatch}){
 let selected=null,replay=null,last=-1,year=0,pickTech=null,pickBranch=null,confirming=false,resetAsk=false
 if(!document.querySelector('#archive-style')){const e=document.createElement('style');e.id='archive-style';e.textContent=`.archive-tabs{display:flex;gap:5px;flex-wrap:wrap}.archive-card{margin:12px 0;padding:13px;background:#f8f1de;color:#354437;border:1px solid #ba9e64;border-radius:8px}.archive-card h3{font:20px KaiTi,serif;margin:8px 0}.archive-card small{display:block;line-height:1.6;color:#6e634c}.archive-scroll{max-height:38dvh;min-height:100px;overflow:auto;overscroll-behavior:contain;line-height:1.95;font-size:14px;padding:0 6px}.archive-scroll p{margin:13px 0}.archive-new{animation:archive-in .45s ease both}.archive-card button,.archive-tabs button{border:1px solid #aa915f;border-radius:5px;background:#354b39;color:#fff3d6;padding:8px;margin:3px;cursor:pointer}.archive-tabs button[aria-pressed=true]{outline:2px solid #ebc46a}.archive-tabs button:disabled{opacity:.45;cursor:default}.archive-actions{display:flex;flex-wrap:wrap;margin-top:9px}.archive-note{font-size:11px}.archive-scroll:focus-visible{outline:2px solid #96753a}@keyframes archive-in{from{opacity:0;transform:translateY(7px)}to{opacity:1;transform:none}}${TECH_CSS}@media(prefers-reduced-motion:reduce){.archive-new{animation:none}}`;document.head.append(e);}
 // —— 包 I2：科技树（立项研发）。分支效果翻成人话，供卡片与择路弹层共用。——
 const effectText=b=>[b.yieldMul&&b.yieldMul!==1?`亩产 ×${b.yieldMul}`:'',b.staminaMul&&b.staminaMul!==1?`收割体力 ×${b.staminaMul}`:'',b.waterCostMul&&b.waterCostMul!==1?`引水工钱 ×${b.waterCostMul}`:'',b.eco?`生态 ${b.eco>0?'+':''}${b.eco}`:'',b.ecoPerSeason?`每季生态 ${b.ecoPerSeason>0?'+':''}${b.ecoPerSeason}`:'',b.pestMul&&b.pestMul!==1?`虫口初值 ×${b.pestMul}`:'',b.pestCut?`虫口初值 −${b.pestCut}`:'',b.crabBonus?'秋后自动捕蟹':''].filter(Boolean).join('　·　')
 function techHTML(s,w,tech){
  const tb=tech||{},done=TECH_IDS.filter(id=>tb[id]?.state==='done')
  const cur=done.map(id=>`${TECHS[id].name}·${esc(TECHS[id].branches[tb[id].branch]?.name||'已定')}`).join('、')
  const notice=w.techNotice?`<div class="tech-notice"><b>天工开物改了规矩。</b>${esc(techNoticeText(w.techLegacy||[]))}<div><button data-tech-notice="1">知道了</button><button data-tech-reset="1">${resetAsk?'确认清档重来？':'重开新局'}</button></div></div>`:''
  const pick=pickTech&&TECHS[pickTech]?(()=>{const def=TECHS[pickTech],miss=techReqMiss(s,pickTech)
   return `<section class="tech-pick" role="dialog" aria-label="${esc(def.name)}择路">
    <h4>${esc(def.name)} · 择一条路子</h4>
    <p class="tech-note">分支一经选定不可更改。立项耗 <b>${def.cost.wen} 文</b>、<b>${def.cost.rice} kg 稻米</b>，约 ${def.seasons} 季，七成成算；失手则投入全废，但路子还算数，可以原样重投。</p>
    ${miss?`<p class="tech-miss">${esc(miss)}</p>`:''}
    <div class="branch-grid">${Object.entries(def.branches).map(([k,b])=>`<button data-tech-branch="${k}" aria-pressed="${pickBranch===k}"><b>${esc(b.name)}</b><span>${esc(b.desc)}</span><em>${effectText(b)}</em></button>`).join('')}</div>
    <div class="tech-pick-actions">${confirming?`<b class="tech-warn">就此定下？这条路定了改不了。</b><button data-tech-confirm="yes">确定，就此定下</button><button data-tech-close="1">再想想</button>`:`<button data-tech-confirm="ask" ${pickBranch?'':'disabled'}>确认立项</button><button data-tech-close="1">收起</button>`}</div>
   </section>`})():''
  const cards=TECH_IDS.map(id=>{
   const def=TECHS[id],st=tb[id]||{state:'idle',branch:null,progress:0},b=st.branch?def.branches[st.branch]:null,miss=st.state==='idle'?techReqMiss(s,id):null
   const cls=st.state==='done'?'done':st.state==='researching'?'running':miss?'locked':'ready'
   const pct=st.state==='done'?100:Math.round((st.progress||0)/def.seasons*100)
   return `<article class="tech-card ${cls}" data-tech-card="${id}">
    <header><b>${def.name}</b><em>${['','一阶','二阶','三阶'][def.tier]||'一阶'}</em>${st.state==='researching'?`<i>研发中 · ${esc(b?.name||'')}</i>`:st.state==='done'?`<i>已就 · ${esc(b?.name||'')}</i>`:''}</header>
    <p>${esc(def.desc)}</p>
    ${st.state==='researching'?`<div class="tech-track" aria-label="研发进度 ${st.progress} / ${def.seasons} 季"><i style="width:${pct}%"></i></div><p class="tech-cost">进度 ${st.progress} / ${def.seasons} 季　·　已投入 ${st.invested?.wen||0} 文、${st.invested?.rice||0} kg　·　开工于第 ${st.startedYear} 年${SEASON_CN[st.startedSeason]||''}季</p>`:''}
    ${st.state==='done'?`<p class="tech-effect">${effectText(b)}</p><p class="tech-cost">研成于第 ${st.doneYear} 年　·　田边的器具已经立起来了</p>`:''}
    ${st.state==='idle'?`<p class="tech-cost">立项耗 ${def.cost.wen} 文 · ${def.cost.rice} kg 稻米　·　约 ${def.seasons} 季　·　七成成算${st.failed?`　·　已失手 ${st.failed} 次`:''}</p>`:''}
    ${miss?`<p class="tech-miss">${esc(miss)}</p>`:''}
    ${st.state==='idle'?`<button data-tech-start="${id}" ${miss?'disabled':''}>${miss?'尚不可立项':'立项研发'}</button>`:''}
   </article>`}).join('')
  return `<details class="tech-tree" open><summary>天工开物 · 立项研发</summary>${notice}<p class="tech-note">天工开物，急不得：立项要投文钱与稻米，研一季进一寸，七成成算——失手了材料尽付东流，路子还在，可重整旗鼓再投。每项科技两条路，择一而终；分支关乎地力与往后的门槛——拖拉机要地力兴旺，走了化肥、药剂这条近道的，得先把地养回来才成。</p>${cur?`<p class="tech-cost">眼下已研成：${cur}</p>`:'<p class="tech-cost">眼下还没有一项科技研成。</p>'}${pick}<div class="tech-grid">${cards}</div></details>`
 }
 function render(message=''){const root=document.querySelector('#system-panel');if(!root)return;const s=getState(),w=s.story||{},a=w.archive||{pages:[0,0,0,0],claimed:[]},limit=chapterLimit(s),tech=w.tech||{};if(last!==limit||year!==s.year){selected=null;replay=null;pickTech=null;pickBranch=null;confirming=false;last=limit;year=s.year;}if(selected===null||selected>limit)selected=CHAPTERS.findIndex((c,i)=>i<=limit&&a.pages[i]<c.paragraphs.length);if(selected<0)selected=limit;const i=selected,c=CHAPTERS[i],n=replay??a.pages[i],done=n>=c.paragraphs.length,focus=root.contains(document.activeElement)?document.activeElement.dataset.archive:null,old=root.querySelector('.archive-scroll'),scroll=old?.dataset.chapter===String(i)?old.scrollTop:0
 root.innerHTML=`<div class="system-title"><span>穿越系统</span><b>京西稻贡米系统</b></div><p class="system-tip">${['春水初生，先把秧脚站稳。','田里有事，先巡田再作抉择。','秋收开仓，留下稻名与成色。','整理旧账，留种给来年。'][CHAPTERS.findIndex(c=>c.season===s.season)]}</p><nav class="archive-tabs" aria-label="四时档案">${CHAPTERS.map((c,j)=>`<button data-chapter="${j}" ${j>limit?'disabled':''} aria-pressed="${j===i}">${['春','夏','秋','冬'][j]}卷${j>limit?'·未至':a.claimed.includes(j)?'·已归档':''}</button>`).join('')}</nav><section class="archive-card" aria-label="主线档案"><small>京西稻贡米系统 · ${replay===null?'阅读进度自动保存':'回看模式'}</small><h3>${c.title}</h3><small class="archive-note">穿越及断代线索为架空剧情，非史实考证。</small><div class="archive-scroll" data-chapter="${i}" tabindex="0" aria-label="本章已展开段落">${n?c.paragraphs.slice(0,n).map((p,j)=>`<p class="${j===n-1?'archive-new':''}">${esc(p)}</p>`).join(''):'<p>卷页已开启。点「继续」逐段读档，也可跳过后随时回看。</p>'}</div><small role="status">${n} / ${c.paragraphs.length} 段${done?' · 本章已读完':''}</small><div class="archive-actions">${done?'<button data-archive="replay">从头回看</button>':'<button data-archive="next">继续</button><button data-archive="skip">跳过本章</button>'}${done&&!a.claimed.includes(i)&&replay===null?'<button data-reward="card">归档 · 古法卡</button><button data-reward="fragment">归档 · 稻种碎片 ×3</button>':''}${done&&i<limit?'<button data-archive="later">下一章</button>':''}${replay!==null?'<button data-archive="exit">结束回看</button>':''}</div><small>${done&&i===limit&&limit<3?'下一卷随季节推进开放；读档不消耗体力。':a.claimed.includes(i)?'本章奖励已领取；回看不重复发放。':'每章只归档一次；读档与归档均不推进季节。'}</small></section>${techHTML(s,w,tech)}<small class="system-log">${(w.systemLog||[]).slice(0,2).map(esc).join(' · ')}</small><div class="system-message" role="status">${esc(message)}</div>`
 root.querySelector('.archive-scroll').scrollTop=scroll
 root.querySelectorAll('[data-chapter]').forEach(b=>{if(b.tagName==='BUTTON')b.onclick=()=>{selected=Number(b.dataset.chapter);replay=null;dispatch({type:'story:trigger',chapter:selected});};})
 root.querySelectorAll('[data-tech-start]').forEach(b=>b.onclick=()=>{pickTech=b.dataset.techStart;pickBranch=null;confirming=false;render()})
 root.querySelectorAll('[data-tech-branch]').forEach(b=>b.onclick=()=>{pickBranch=b.dataset.techBranch;confirming=false;render()})
 root.querySelectorAll('[data-tech-confirm]').forEach(b=>b.onclick=()=>{if(b.dataset.techConfirm==='ask'){confirming=true;render();return}const id=pickTech,br=pickBranch;confirming=false;pickTech=null;pickBranch=null;dispatch({type:'story:tech',tech:id,branch:br})})
 root.querySelectorAll('[data-tech-close]').forEach(b=>b.onclick=()=>{pickTech=null;pickBranch=null;confirming=false;render()})
 root.querySelectorAll('[data-tech-notice]').forEach(b=>b.onclick=()=>dispatch({type:'story:tech-notice'}))
 root.querySelectorAll('[data-tech-reset]').forEach(b=>b.onclick=()=>{if(!resetAsk){resetAsk=true;render();return}try{localStorage.removeItem(SAVE_KEY);localStorage.removeItem(SAVE_KEY+'-demo');}catch{}location.reload()})
 root.querySelectorAll('[data-reward]').forEach(b=>b.onclick=()=>dispatch({type:'story:resolve',chapter:i,reward:b.dataset.reward}))
 root.querySelectorAll('[data-archive]').forEach(b=>b.onclick=()=>{const k=b.dataset.archive;if(k==='replay'){replay=0;render();}else if(k==='exit'){replay=null;render();}else if(k==='later'){selected=i+1;replay=null;dispatch({type:'story:trigger',chapter:selected});}else{if(replay!==null){replay=k==='skip'?c.paragraphs.length:Math.min(c.paragraphs.length,replay+1);render();}else dispatch({type:k==='skip'?'story:skip':'story:read',chapter:i});const box=root.querySelector('.archive-scroll');if(box)box.scrollTo({top:box.scrollHeight,behavior:'auto'});}})
 if(focus)(root.querySelector(`[data-archive="${focus}"]`)||root.querySelector('[data-archive]'))?.focus({preventScroll:true})
 }
 return {render}
}
